/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import javax.swing.JButton;
import modelo.Carrito;

/**
 *
 * @author Lenovo
 */
public class VistaPago extends javax.swing.JFrame {
   

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPago.class.getName());

    private Carrito carrito;

    public VistaPago(Carrito carrito) {
        initComponents();
    setLocationRelativeTo(null);
    this.carrito = carrito;
    lblTotal.setText("Total: $" + carrito.getTotal());
  
    }
    public JButton getBtnPagar() {
    return btnPagar;
    }


    public javax.swing.JButton getBtnCancelar() {
    return btnCancelar;
    }

    public javax.swing.JButton getBtnRegresar() {
    return btnRegresar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbTransferencia = new javax.swing.JRadioButton();
        rbPaypal = new javax.swing.JRadioButton();
        rbTarjeta = new javax.swing.JRadioButton();
        panelMetodo = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        lblFondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondolet.png"))); // NOI18N
        jLabel1.setText("MÉTODO DE PAGO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 20, 400, 40);

        lblTotal.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: ");
        lblTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblTotal);
        lblTotal.setBounds(30, 80, 230, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VuelosFis  (1).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 10, 60, 50);

        buttonGroup1.add(rbTransferencia);
        rbTransferencia.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        rbTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        rbTransferencia.setText("Transferencia");
        rbTransferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbTransferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonS.png"))); // NOI18N
        rbTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTransferenciaActionPerformed(evt);
            }
        });
        jPanel1.add(rbTransferencia);
        rbTransferencia.setBounds(230, 150, 140, 30);

        buttonGroup1.add(rbPaypal);
        rbPaypal.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        rbPaypal.setForeground(new java.awt.Color(255, 255, 255));
        rbPaypal.setText("Paypal");
        rbPaypal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbPaypal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbPaypal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonS.png"))); // NOI18N
        rbPaypal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPaypalActionPerformed(evt);
            }
        });
        jPanel1.add(rbPaypal);
        rbPaypal.setBounds(430, 150, 120, 30);

        buttonGroup1.add(rbTarjeta);
        rbTarjeta.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        rbTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        rbTarjeta.setText("Tarjeta");
        rbTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbTarjeta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonS.png"))); // NOI18N
        rbTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(rbTarjeta);
        rbTarjeta.setBounds(40, 150, 110, 30);

        javax.swing.GroupLayout panelMetodoLayout = new javax.swing.GroupLayout(panelMetodo);
        panelMetodo.setLayout(panelMetodoLayout);
        panelMetodoLayout.setHorizontalGroup(
            panelMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        panelMetodoLayout.setVerticalGroup(
            panelMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(panelMetodo);
        panelMetodo.setBounds(40, 210, 500, 200);

        btnContinuar.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.jpg"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar);
        btnContinuar.setBounds(420, 490, 150, 35);

        btnCancelar.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonT (1).png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(120, 425, 150, 40);

        btnRegresar.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.jpg"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(20, 490, 150, 35);

        btnPagar.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonT (1).png"))); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagar);
        btnPagar.setBounds(340, 430, 150, 40);

        lblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pago 2.jpg"))); // NOI18N
        jPanel1.add(lblFondo2);
        lblFondo2.setBounds(0, -10, 600, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTransferenciaActionPerformed
    panelMetodo.removeAll();
    panelMetodo.setLayout(new java.awt.GridLayout(3,2,10,10));

    panelMetodo.add(new javax.swing.JLabel("Banco:"));
    panelMetodo.add(new javax.swing.JTextField());

    panelMetodo.add(new javax.swing.JLabel("Cuenta:"));
    panelMetodo.add(new javax.swing.JTextField());

    panelMetodo.add(new javax.swing.JLabel("Referencia:"));
    panelMetodo.add(new javax.swing.JTextField());

    panelMetodo.revalidate();
    panelMetodo.repaint();
    }//GEN-LAST:event_rbTransferenciaActionPerformed

    private void rbPaypalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPaypalActionPerformed
        // TODO add your handling code here: panelMetodo.removeAll();
    panelMetodo.setLayout(new java.awt.GridLayout(2,2,10,10));

    panelMetodo.add(new javax.swing.JLabel("Correo PayPal:"));
    panelMetodo.add(new javax.swing.JTextField());

    panelMetodo.add(new javax.swing.JLabel("Contraseña:"));
    panelMetodo.add(new javax.swing.JPasswordField());

    panelMetodo.revalidate();
    panelMetodo.repaint();
    }//GEN-LAST:event_rbPaypalActionPerformed

    private void rbTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTarjetaActionPerformed
    panelMetodo.removeAll();
panelMetodo.setLayout(new java.awt.GridBagLayout());
panelMetodo.setBorder(
    javax.swing.BorderFactory.createTitledBorder(
        javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE, 2),
        "Datos de la Tarjeta",
        javax.swing.border.TitledBorder.CENTER,
        javax.swing.border.TitledBorder.TOP,
        new java.awt.Font("SimSun", 1, 18),
        java.awt.Color.WHITE
    )
);

java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
gbc.insets = new java.awt.Insets(10, 10, 10, 10);
gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;

// Nombre titular
gbc.gridx = 0; gbc.gridy = 0;
panelMetodo.add(new javax.swing.JLabel("Nombre del titular:"), gbc);

gbc.gridx = 1;
panelMetodo.add(new javax.swing.JTextField(15), gbc);

// Número tarjeta
gbc.gridx = 0; gbc.gridy = 1;
panelMetodo.add(new javax.swing.JLabel("Número de tarjeta:"), gbc);

gbc.gridx = 1;
panelMetodo.add(new javax.swing.JTextField(15), gbc);

// CVV
gbc.gridx = 0; gbc.gridy = 2;
panelMetodo.add(new javax.swing.JLabel("CVV:"), gbc);

gbc.gridx = 1;
panelMetodo.add(new javax.swing.JTextField(5), gbc);

// Fecha vencimiento
gbc.gridx = 0; gbc.gridy = 3;
panelMetodo.add(new javax.swing.JLabel("Fecha de vencimiento:"), gbc);

gbc.gridx = 1;
panelMetodo.add(new javax.swing.JTextField(10), gbc);

panelMetodo.revalidate();
panelMetodo.repaint();

    }//GEN-LAST:event_rbTarjetaActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
         if (!rbTarjeta.isSelected() &&
        !rbTransferencia.isSelected() &&
        !rbPaypal.isSelected()) {

        javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione un método de pago");
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(this,
        "Datos correctos. Presione PAGAR para finalizar.");
    
    btnPagar.setEnabled(true);
    }//GEN-LAST:event_btnContinuarActionPerformed
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
    Carrito carrito = new Carrito();
    new VistaPago(carrito).setVisible(true);
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelMetodo;
    private javax.swing.JRadioButton rbPaypal;
    private javax.swing.JRadioButton rbTarjeta;
    private javax.swing.JRadioButton rbTransferencia;
    // End of variables declaration//GEN-END:variables
}
