/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Boleto;
import modelo.Carrito;

/**
 *
 * @author Lenovo
 */
public class VistaCarrito extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCarrito.class.getName());

    /**
     * Creates new form VistaCarrito
     */
  

    
    private Carrito carrito;
    private DefaultListModel<Boleto> modeloLista;
    

    public VistaCarrito(Carrito carrito) {
    initComponents();
    setLocationRelativeTo(null);
    
    if (getClass().getResource("/Imagenes/Boton.jpg") == null) {
    System.out.println("Imagen NO encontrada 😢");
    } else {
    System.out.println("Imagen encontrada ✔️");
    }

     // Asigna la imagen a un botón
     btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.jpg")));
    this.carrito = carrito;
    modeloLista = new DefaultListModel<>();
    listaBoletos.setModel(modeloLista);

    cargarLista();
    }

    
    public javax.swing.JButton getBtnContinuar() {
    return btnContinuar; // ✔️
    }

    
    private void cargarLista() {
        modeloLista.clear();
        for (Boleto b : carrito.getBoletos()) {
            modeloLista.addElement(b);
        }
        lblTotal.setText("Total a pagar: $" + carrito.getTotal());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        listaBoletos = new javax.swing.JList<>();
        lblTotal = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jScrollPane12.setViewportView(listaBoletos);

        jPanel1.add(jScrollPane12);
        jScrollPane12.setBounds(30, 80, 260, 280);

        lblTotal.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: ");
        lblTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTotal);
        lblTotal.setBounds(30, 380, 330, 50);

        btnRegresar.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.jpg"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(30, 470, 170, 40);

        btnEliminar.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonT (1).png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(380, 320, 150, 40);

        btnContinuar.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.jpg"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar);
        btnContinuar.setBounds(400, 470, 170, 40);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondolet.png"))); // NOI18N
        jLabel1.setText("BOLETOS A COMPRAR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 20, 390, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VuelosFis  (1).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 10, 60, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boletos (1) .png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 140, 200, 160);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pago 2.jpg"))); // NOI18N
        jPanel1.add(lblFondo);
        lblFondo.setBounds(0, 0, 600, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     int index = listaBoletos.getSelectedIndex();

    if (index == -1) {
        JOptionPane.showMessageDialog(this,
            "Selecciona un boleto primero");
        return;
    }

    int op = JOptionPane.showConfirmDialog(this,
        "¿Seguro de eliminar este boleto?",
        "Confirmar",
        JOptionPane.YES_NO_OPTION);

    if (op == JOptionPane.YES_OPTION) {
        carrito.eliminar(index);
        modeloLista.remove(index);
        lblTotal.setText("Total a pagar: $" + carrito.getTotal());
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
       

    
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<modelo.Boleto> listaBoletos;
    // End of variables declaration//GEN-END:variables
}
