/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;
import controlador.ControladorSeleccionVuelo;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class VistaDestino extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaDestino.class.getName());


    /**
     * Creates new form InterfazPrincipal
     */
    public VistaDestino() {
        initComponents();
        dateChooserFecha.setDateFormatString("dd/MM/yyyy");
        dateChooserFecha.setMinSelectableDate(new java.util.Date());
        

    }
    
    public Date getFechaVuelo() {
        return dateChooserFecha.getDate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new recursos.imagenes.PanelImagen();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbOrigen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbDestino = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarVuelos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnMenosDiscapacitado = new javax.swing.JButton();
        Discapacidad = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTotalPasajeros = new javax.swing.JTextField();
        btnMasDiscapacitado = new javax.swing.JButton();
        btnMasAdultoMayor = new javax.swing.JButton();
        btnMenosNinio = new javax.swing.JButton();
        btnMasNinio = new javax.swing.JButton();
        btnMenosAdulto = new javax.swing.JButton();
        btnMenosAdultoMayor = new javax.swing.JButton();
        btnMasAdulto = new javax.swing.JButton();
        dateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        lblFondo3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblFondo2 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(51, 255, 204));
        PanelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelFondo.setLayout(null);

        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonT.png"))); // NOI18N
        jLabel2.setText("ORIGEN:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 20, 160, 50);

        cbOrigen.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        cbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ecuador", "Colombia", "Chile", "Argentina" }));
        cbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrigenActionPerformed(evt);
            }
        });
        jPanel3.add(cbOrigen);
        cbOrigen.setBounds(50, 80, 140, 40);

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonT.png"))); // NOI18N
        jLabel3.setText("DESTINO:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(270, 20, 170, 50);

        cbDestino.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        cbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ecuador", "Colombia", "Chile", "Argentina" }));
        cbDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinoActionPerformed(evt);
            }
        });
        jPanel3.add(cbDestino);
        cbDestino.setBounds(280, 80, 140, 40);

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel4.setText("NÚMERO DE PASAJEROS:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(40, 280, 210, 30);

        btnBuscarVuelos.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnBuscarVuelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.jpg"))); // NOI18N
        btnBuscarVuelos.setText("BUSCAR VUELOS");
        btnBuscarVuelos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVuelosActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarVuelos);
        btnBuscarVuelos.setBounds(530, 270, 200, 40);

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel5.setText("Adultos:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(350, 190, 90, 22);

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel6.setText("Niños:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(220, 190, 70, 22);

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel7.setText("Adulto mayor:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(40, 190, 140, 22);

        btnMenosDiscapacitado.setBackground(new java.awt.Color(204, 204, 255));
        btnMenosDiscapacitado.setText("-");
        btnMenosDiscapacitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosDiscapacitadoActionPerformed(evt);
            }
        });
        jPanel3.add(btnMenosDiscapacitado);
        btnMenosDiscapacitado.setBounds(250, 220, 50, 40);

        Discapacidad.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        Discapacidad.setText("Discapacitado:");
        jPanel3.add(Discapacidad);
        Discapacidad.setBounds(470, 190, 150, 22);

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner.png"))); // NOI18N
        jLabel8.setText("Total de pasajeros:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 130, 300, 50);

        txtTotalPasajeros.setEnabled(false);
        txtTotalPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPasajerosActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotalPasajeros);
        txtTotalPasajeros.setBounds(250, 280, 90, 30);

        btnMasDiscapacitado.setBackground(new java.awt.Color(204, 255, 255));
        btnMasDiscapacitado.setText("+");
        btnMasDiscapacitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasDiscapacitadoActionPerformed(evt);
            }
        });
        jPanel3.add(btnMasDiscapacitado);
        btnMasDiscapacitado.setBounds(190, 220, 50, 40);

        btnMasAdultoMayor.setBackground(new java.awt.Color(204, 255, 255));
        btnMasAdultoMayor.setText("+");
        btnMasAdultoMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasAdultoMayorActionPerformed(evt);
            }
        });
        jPanel3.add(btnMasAdultoMayor);
        btnMasAdultoMayor.setBounds(330, 220, 50, 40);

        btnMenosNinio.setBackground(new java.awt.Color(204, 204, 255));
        btnMenosNinio.setText("-");
        btnMenosNinio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosNinioActionPerformed(evt);
            }
        });
        jPanel3.add(btnMenosNinio);
        btnMenosNinio.setBounds(390, 220, 50, 40);

        btnMasNinio.setBackground(new java.awt.Color(204, 255, 255));
        btnMasNinio.setText("+");
        btnMasNinio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasNinioActionPerformed(evt);
            }
        });
        jPanel3.add(btnMasNinio);
        btnMasNinio.setBounds(480, 220, 46, 40);

        btnMenosAdulto.setBackground(new java.awt.Color(204, 204, 255));
        btnMenosAdulto.setFont(new java.awt.Font("SimSun", 3, 24)); // NOI18N
        btnMenosAdulto.setText("-");
        btnMenosAdulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosAdultoActionPerformed(evt);
            }
        });
        jPanel3.add(btnMenosAdulto);
        btnMenosAdulto.setBounds(110, 220, 50, 40);

        btnMenosAdultoMayor.setBackground(new java.awt.Color(204, 204, 255));
        btnMenosAdultoMayor.setText("-");
        btnMenosAdultoMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosAdultoMayorActionPerformed(evt);
            }
        });
        jPanel3.add(btnMenosAdultoMayor);
        btnMenosAdultoMayor.setBounds(540, 220, 50, 40);

        btnMasAdulto.setBackground(new java.awt.Color(153, 255, 255));
        btnMasAdulto.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnMasAdulto.setText("+");
        btnMasAdulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasAdultoActionPerformed(evt);
            }
        });
        jPanel3.add(btnMasAdulto);
        btnMasAdulto.setBounds(50, 220, 50, 40);
        jPanel3.add(dateChooserFecha);
        dateChooserFecha.setBounds(500, 80, 220, 40);

        jLabel10.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonT.png"))); // NOI18N
        jLabel10.setText("FECHA DE VUELO:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel10);
        jLabel10.setBounds(510, 30, 160, 40);

        lblFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DestinoFono.jpg"))); // NOI18N
        jPanel3.add(lblFondo3);
        lblFondo3.setBounds(-10, 0, 750, 330);

        PanelFondo.add(jPanel3);
        jPanel3.setBounds(120, 220, 740, 330);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CONTACTANOS EN NUESTRAS REDES SOCIALES");
        PanelFondo.add(jLabel9);
        jLabel9.setBounds(360, 560, 360, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-VuelosFIS.png"))); // NOI18N
        PanelFondo.add(jLabel11);
        jLabel11.setBounds(390, 10, 200, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/instagram.png"))); // NOI18N
        PanelFondo.add(jLabel1);
        jLabel1.setBounds(340, 590, 110, 110);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tiktok.png"))); // NOI18N
        PanelFondo.add(jLabel12);
        jLabel12.setBounds(70, 600, 100, 100);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equis.png"))); // NOI18N
        PanelFondo.add(jLabel14);
        jLabel14.setBounds(590, 600, 100, 100);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facebook.jpg"))); // NOI18N
        PanelFondo.add(jLabel13);
        jLabel13.setBounds(830, 590, 100, 100);

        lblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DestinoAvion.jpg"))); // NOI18N
        PanelFondo.add(lblFondo2);
        lblFondo2.setBounds(0, -30, 1090, 240);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DestinoCielo.jpg"))); // NOI18N
        PanelFondo.add(lblFondo);
        lblFondo.setBounds(0, 60, 1070, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrigenActionPerformed

    private void cbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDestinoActionPerformed

    private void btnMenosAdultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosAdultoActionPerformed
        
    }//GEN-LAST:event_btnMenosAdultoActionPerformed

    private void btnMasAdultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasAdultoActionPerformed
        
    }//GEN-LAST:event_btnMasAdultoActionPerformed

    private void btnMenosNinioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosNinioActionPerformed
       
    }//GEN-LAST:event_btnMenosNinioActionPerformed

    private void btnMasNinioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasNinioActionPerformed
        
    }//GEN-LAST:event_btnMasNinioActionPerformed

    private void btnMenosAdultoMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosAdultoMayorActionPerformed
        
    }//GEN-LAST:event_btnMenosAdultoMayorActionPerformed

    private void btnMasAdultoMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasAdultoMayorActionPerformed
        
    }//GEN-LAST:event_btnMasAdultoMayorActionPerformed

    private void btnMenosDiscapacitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosDiscapacitadoActionPerformed
        
    }//GEN-LAST:event_btnMenosDiscapacitadoActionPerformed

    private void btnMasDiscapacitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasDiscapacitadoActionPerformed
        
    }//GEN-LAST:event_btnMasDiscapacitadoActionPerformed

    private void txtTotalPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPasajerosActionPerformed

    private void btnBuscarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVuelosActionPerformed
   
    }//GEN-LAST:event_btnBuscarVuelosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaDestino().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Discapacidad;
    private javax.swing.JPanel PanelFondo;
    public javax.swing.JButton btnBuscarVuelos;
    public javax.swing.JButton btnMasAdulto;
    public javax.swing.JButton btnMasAdultoMayor;
    public javax.swing.JButton btnMasDiscapacitado;
    public javax.swing.JButton btnMasNinio;
    public javax.swing.JButton btnMenosAdulto;
    public javax.swing.JButton btnMenosAdultoMayor;
    public javax.swing.JButton btnMenosDiscapacitado;
    public javax.swing.JButton btnMenosNinio;
    public javax.swing.JComboBox<String> cbDestino;
    public javax.swing.JComboBox<String> cbOrigen;
    private com.toedter.calendar.JDateChooser dateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblFondo3;
    public javax.swing.JTextField txtTotalPasajeros;
    // End of variables declaration//GEN-END:variables
}

