/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorDetallesCompras;

/**
 *
 * @author Lenovo
 */
public class VistaSeleccionVuelo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaSeleccionVuelo.class.getName());

    /**
     * Creates new form VistaSeleccionVuelo
     */
    public VistaSeleccionVuelo() {
        initComponents();
    }
    public javax.swing.JButton getBtnContinuar() {
    return btnContinuar;
}

public javax.swing.JButton getBtnVuelo1() {
    return btnVuelo1;
}

public javax.swing.JButton getBtnVuelo2() {
    return btnVuelo2;
}

public javax.swing.JButton getBtnVuelo3() {
    return btnVuelo3;
}

public javax.swing.JRadioButton getRbIda() {
    return rbIda;
}

public javax.swing.JRadioButton getRbIdaVuelta() {
    return rbIdaVuelta;
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbIda = new javax.swing.JRadioButton();
        rbIdaVuelta = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnVuelo1 = new javax.swing.JButton();
        btnVuelo2 = new javax.swing.JButton();
        btnVuelo3 = new javax.swing.JButton();
        lblFonod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VuelosFis.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(900, 20, 90, 90);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bannner.jpg"))); // NOI18N
        jLabel1.setText("SELECCIÓN DE VUELOS");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-3, -4, 1010, 150);

        rbIda.setBackground(new java.awt.Color(102, 255, 255));
        buttonGroup1.add(rbIda);
        rbIda.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        rbIda.setText("Vuelo de Ida");
        rbIda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIdaActionPerformed(evt);
            }
        });
        jPanel1.add(rbIda);
        rbIda.setBounds(40, 160, 200, 46);

        rbIdaVuelta.setBackground(new java.awt.Color(102, 255, 255));
        buttonGroup1.add(rbIdaVuelta);
        rbIdaVuelta.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        rbIdaVuelta.setText("Vuelo de ida y de regreso");
        jPanel1.add(rbIdaVuelta);
        rbIdaVuelta.setBounds(290, 160, 370, 46);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boletos.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 420, 320, 220);

        btnContinuar.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonT.png"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar);
        btnContinuar.setBounds(800, 560, 150, 40);

        jPanel2.setLayout(null);

        btnVuelo1.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        btnVuelo1.setText(" 08:05 - 12:34                     USD 246.76");
        btnVuelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuelo1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVuelo1);
        btnVuelo1.setBounds(0, 0, 930, 60);

        btnVuelo2.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        btnVuelo2.setText(" 22:05 - 10:04                     USD 175.46");
        btnVuelo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuelo2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVuelo2);
        btnVuelo2.setBounds(0, 60, 930, 60);

        btnVuelo3.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        btnVuelo3.setText("14:05 - 16:04                      USD 210.46");
        btnVuelo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuelo3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVuelo3);
        btnVuelo3.setBounds(0, 120, 930, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 230, 930, 180);

        lblFonod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondosel.jpg"))); // NOI18N
        jPanel1.add(lblFonod);
        lblFonod.setBounds(0, 0, 1010, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVuelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuelo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVuelo1ActionPerformed

    private void btnVuelo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuelo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVuelo2ActionPerformed

    private void btnVuelo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuelo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVuelo3ActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
    
    
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void rbIdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaSeleccionVuelo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnVuelo1;
    private javax.swing.JButton btnVuelo2;
    private javax.swing.JButton btnVuelo3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFonod;
    private javax.swing.JRadioButton rbIda;
    private javax.swing.JRadioButton rbIdaVuelta;
    // End of variables declaration//GEN-END:variables
}
