package vista;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import javax.swing.JFileChooser;
import modelo.ModeloCarrito;
import modelo.ModeloBoleto;

public class VistaFactura extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaFactura.class.getName());
    private ModeloCarrito carrito;
    private javax.swing.JTextArea txtAreaTicket;
    private javax.swing.JScrollPane scrollPanel;

    /**
     * Creates new form VistaFactura
     */
    public VistaFactura(ModeloCarrito carrito) {
    initComponents();
    this.carrito = carrito;
    configuracionAdicional();
    generarFactura();
}
    
    
    private void configuracionAdicional() {
        setTitle("Factura de Vuelo");
        setLocationRelativeTo(null);
        
        // Creamos el área de texto y la configuramos (SOLO AQUÍ)
        txtAreaTicket = new javax.swing.JTextArea();
        txtAreaTicket.setEditable(false);
        txtAreaTicket.setFont(new Font("Monospaced", Font.PLAIN, 12)); // Fuente para que las columnas alineen
        
        scrollPanel = new javax.swing.JScrollPane(txtAreaTicket);
        
        // La añadimos al panel que ya tenías
        panelFactura.setLayout(new java.awt.BorderLayout());
        panelFactura.add(scrollPanel, java.awt.BorderLayout.CENTER);
        panelFactura.add(btnGuardar, java.awt.BorderLayout.SOUTH);
    }

    // Método para que el Controlador o Main le mande el texto
    public void setTextoTicket(String texto) {
        if (txtAreaTicket != null) {
            txtAreaTicket.setText(texto);
        } else {
            // Esto solo ocurriría si llamas al método antes de que se complete el constructor
            System.err.println("Error: txtAreaTicket es NULL al intentar establecer texto.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFactura = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFacturaLayout = new javax.swing.GroupLayout(panelFactura);
        panelFactura.setLayout(panelFacturaLayout);
        panelFacturaLayout.setHorizontalGroup(
            panelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFacturaLayout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFacturaLayout.setVerticalGroup(
            panelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFacturaLayout.createSequentialGroup()
                .addGap(0, 457, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String contenido = txtAreaTicket.getText();
        if (contenido == null || contenido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay datos para guardar");
            return;
    }//GEN-LAST:event_btnGuardarActionPerformed
    JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione dónde guardar su factura");
        fileChooser.setSelectedFile(new File("Factura_Vuelo.txt"));

        int userSelection = fileChooser.showSaveDialog(this);

        // Usamos 0 que es el valor de JFileChooser.APPROVE_VALUE
        if (userSelection == 0) { 
            File archivoAguardar = fileChooser.getSelectedFile();
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivoAguardar))) {
                writer.write(contenido);
                JOptionPane.showMessageDialog(this, "Factura guardada con éxito en:\n" + archivoAguardar.getAbsolutePath());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + e.getMessage());
            }
        }
    }                                          
    /**
     * @param args the command line arguments
     */
    private void generarFactura() {
    StringBuilder sb = new StringBuilder();

    sb.append("========= FACTURA DE VUELO =========\n\n");

    int i = 1;
    for (ModeloBoleto b : carrito.getBoletos()) {
        sb.append("Boleto ").append(i++).append("\n");
        sb.append("Nombre: ").append(b.getNombre()).append("\n");
        sb.append("Clase: ").append(b.getClaseVuelo()).append("\n");
        sb.append("Vuelo: ").append(b.getVueloSeleccionado()).append("\n");
        sb.append("Tipo: ").append(b.getTipoVuelo()).append("\n");
        sb.append("Maletas: ").append(b.isTieneMaletas() ? "Sí" : "No").append("\n");
        sb.append("Precio: $").append(b.getPrecio()).append("\n");
        sb.append("----------------------------------\n");
    }

    sb.append("\nTOTAL PAGADO: $")
      .append(String.format("%.2f", carrito.getTotal()));

    setTextoTicket(sb.toString());
}

    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel panelFactura;
    // End of variables declaration//GEN-END:variables
}
