/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import modelo.ModeloCarrito;
/**
 *
 * @author chich
 */
public class VistaDetallesCompra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaDetallesCompra.class.getName());

    /**
     * Creates new form VDetallesCompra
     */
    public VistaDetallesCompra() {
    initComponents();
    // Configurar los botones toggle
    BtnMaletas.addActionListener(e -> {
        if (BtnMaletas.isSelected()) {
            BtnMaletas.setText("SÍ");
        } else {
            BtnMaletas.setText("NO");
        }
    });
    
    BtnVueloRegreso.addActionListener(e -> {
        if (BtnVueloRegreso.isSelected()) {
            BtnVueloRegreso.setText("SÍ");
        } else {
            BtnVueloRegreso.setText("NO");
        }
    });
    
    // Inicializar texto de los botones
    BtnMaletas.setText("NO");
    BtnVueloRegreso.setText("NO");    
    // Cambiar texto del botón (NO crear uno nuevo)
    btnGuardarInformacion.setText("GUARDAR INFORMACIÓN");
    
    // Si quieres cambiar el icono de btnGuardarInformacion:
    // btnGuardarInformacion.setIcon(...);
    
} // ← CIERRA EL CONSTRUCTOR AQUÍ

    // Añade este método getter en la clase VistaDetallesCompra:

public javax.swing.JButton getBtnGuardarInformacion() {
    return btnGuardarInformacion;
}
// LOS GETTERS VAN FUERA, COMO MÉTODOS SEPARADOS:
public javax.swing.JButton getBtnSiguiente() {
    return BtnSiguiente;
}

public javax.swing.JTextField getTxtNumeroPasajeros() {
    return TxtNumeroPasajeros;
}

public javax.swing.JToggleButton getBtnMaletas() {
    return BtnMaletas;
}

public javax.swing.JToggleButton getBtnVueloRegreso() {
    return BtnVueloRegreso;
}

public javax.swing.JTextField getTxtNombre() {
    return TxtNombre;
}

public javax.swing.JTextField getTxtCedula() {
    return TxtCedula;
}

public javax.swing.JTextField getTxtPasaporte() {
    return TxtPasaporte;
}

public javax.swing.JComboBox<String> getComboClase() {
    return ComboTiposVuelo;
}

public javax.swing.JTable getTblServicios() {
    return tblServicios;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNumeroPasajeros = new javax.swing.JTextField();
        BtnVueloRegreso = new javax.swing.JToggleButton();
        BtnMaletas = new javax.swing.JToggleButton();
        BtnSiguiente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardarInformacion = new javax.swing.JButton();
        TxtPasaporte = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtCedula = new javax.swing.JTextField();
        ComboTiposVuelo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        LblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VuelosFis.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(890, 40, 120, 80);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button11.jpg"))); // NOI18N
        jLabel1.setText("¿TIENE MALETAS?");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setInheritsPopupMenu(false);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 140, 250, 50);

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoDetalles.jpg"))); // NOI18N
        jLabel2.setText("DETALLES DE BOLETOS");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, 30, 1060, 90);

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button11.jpg"))); // NOI18N
        jLabel3.setText("NÚMERO DE PASAJEROS");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setInheritsPopupMenu(false);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 140, 250, 50);

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button11.jpg"))); // NOI18N
        jLabel4.setText("VUELO DE REGRESO");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(730, 140, 250, 50);

        TxtNumeroPasajeros.setBackground(new java.awt.Color(204, 255, 255));
        TxtNumeroPasajeros.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        TxtNumeroPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeroPasajerosActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNumeroPasajeros);
        TxtNumeroPasajeros.setBounds(440, 210, 160, 40);

        BtnVueloRegreso.setBackground(new java.awt.Color(204, 255, 255));
        BtnVueloRegreso.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        BtnVueloRegreso.setText("NO");
        BtnVueloRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVueloRegresoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVueloRegreso);
        BtnVueloRegreso.setBounds(790, 210, 140, 40);

        BtnMaletas.setBackground(new java.awt.Color(204, 255, 255));
        BtnMaletas.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        BtnMaletas.setText("NO");
        BtnMaletas.setBorder(null);
        BtnMaletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMaletasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMaletas);
        BtnMaletas.setBounds(110, 210, 150, 40);

        BtnSiguiente.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        BtnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        BtnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonT.png"))); // NOI18N
        BtnSiguiente.setText("SIGUIENTE");
        BtnSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSiguiente);
        BtnSiguiente.setBounds(890, 630, 150, 44);

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button11.jpg"))); // NOI18N
        jLabel5.setText("NOMBRE");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 280, 250, 50);

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button11.jpg"))); // NOI18N
        jLabel6.setText("PASAPORTE");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 560, 250, 50);

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button11.jpg"))); // NOI18N
        jLabel7.setText("CÉDULA");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 430, 260, 40);

        btnGuardarInformacion.setBackground(new java.awt.Color(204, 255, 255));
        btnGuardarInformacion.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnGuardarInformacion.setText("Guardar información");
        btnGuardarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarInformacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarInformacion);
        btnGuardarInformacion.setBounds(390, 630, 290, 30);

        TxtPasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasaporteActionPerformed(evt);
            }
        });
        jPanel1.add(TxtPasaporte);
        TxtPasaporte.setBounds(50, 630, 250, 40);

        TxtNombre.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNombre);
        TxtNombre.setBounds(50, 360, 250, 40);

        TxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCedula);
        TxtCedula.setBounds(50, 500, 250, 40);

        ComboTiposVuelo.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        ComboTiposVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economica", "Ejecutiva", "Premium" }));
        ComboTiposVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTiposVueloActionPerformed(evt);
            }
        });
        jPanel1.add(ComboTiposVuelo);
        ComboTiposVuelo.setBounds(690, 290, 150, 28);

        tblServicios.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblServicios);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(390, 360, 470, 250);

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button11.jpg"))); // NOI18N
        jLabel8.setText("TIPO DE VUELO");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 280, 250, 50);

        LblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/donfobu.jpg"))); // NOI18N
        jPanel1.add(LblFondo);
        LblFondo.setBounds(0, 0, 1070, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNumeroPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeroPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeroPasajerosActionPerformed

    private void BtnVueloRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVueloRegresoActionPerformed

    }//GEN-LAST:event_BtnVueloRegresoActionPerformed

    private void BtnMaletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMaletasActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
     
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCedulaActionPerformed

    private void TxtPasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasaporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasaporteActionPerformed

    private void ComboTiposVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTiposVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTiposVueloActionPerformed

    private void btnGuardarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarInformacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaDetallesCompra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton BtnMaletas;
    public javax.swing.JButton BtnSiguiente;
    public javax.swing.JToggleButton BtnVueloRegreso;
    private javax.swing.JComboBox<String> ComboTiposVuelo;
    private javax.swing.JLabel LblFondo;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JTextField TxtNombre;
    public javax.swing.JTextField TxtNumeroPasajeros;
    private javax.swing.JTextField TxtPasaporte;
    private javax.swing.JButton btnGuardarInformacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServicios;
    // End of variables declaration//GEN-END:variables
}
