/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorAsientos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.ModeloAsientos;
import modelo.ModeloEstadoAsiento;
import modelo.ModeloVuelo;

public class VistaAsientos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAsientos.class.getName());

    /**
     * Creates new form VistaAsientos
     */
    
    private ImageIcon iconDisponible;
    private ImageIcon iconSeleccionado;
    private ImageIcon iconOcupado;
    private ModeloVuelo vuelo;
    private ControladorAsientos controlador;
    private int maxAsientos;
    private int asientosSeleccionados;

    public VistaAsientos(int maxAsientos) {
        this.maxAsientos = maxAsientos;
        this.asientosSeleccionados = 0;
        
        initComponents();

        vuelo = new ModeloVuelo();
        controlador = new ControladorAsientos(maxAsientos);

        // Layouts EXACTOS como la imagen
        jPanel2.setLayout(new GridLayout(8, 3, 10, 10));
        jPanel4.setLayout(new GridLayout(8, 3, 10, 10));

        // Colores café
        jPanel2.setBackground(new Color(153, 51, 0));
        jPanel4.setBackground(new Color(153, 51, 0));

        // Cargar íconos
        iconDisponible   = new ImageIcon(getClass().getResource("/imagenes/asientos-disponibles.png"));
        iconSeleccionado = new ImageIcon(getClass().getResource("/imagenes/asientos-seleccionados.png"));
        iconOcupado      = new ImageIcon(getClass().getResource("/imagenes/asientos-ocupados.png"));

        // Cargar asientos
        cargarAsientos();
    }
    
    private void cargarAsientos() {

        List<ModeloAsientos> lista = vuelo.getAsientos();

        jPanel2.removeAll();
        jPanel4.removeAll();

        int index = 0;

        for (int fila = 1; fila <= 8; fila++) {

            // IZQUIERDA: A B C
            for (int i = 0; i < 3; i++) {
                crearBoton(jPanel2, lista.get(index++));
            }

            // DERECHA: D E F
            for (int i = 0; i < 3; i++) {
                crearBoton(jPanel4, lista.get(index++));
            }
        }

        jPanel2.revalidate();
        jPanel2.repaint();
        jPanel4.revalidate();
        jPanel4.repaint();
    }


    private void crearBoton(JPanel panel, ModeloAsientos asiento) {

        JButton btn = new JButton();
        btn.setPreferredSize(new Dimension(40, 40));
        btn.setBorderPainted(false);
        btn.setContentAreaFilled(false);
        btn.setFocusPainted(false);
        
        btn.setText(asiento.getCodigo());
        btn.setHorizontalTextPosition(JButton.CENTER);
        btn.setVerticalTextPosition(JButton.CENTER);
        btn.setForeground(Color.BLACK);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 5));

        actualizarIcono(btn, asiento);

        if (asiento.getEstado() != ModeloEstadoAsiento.OCUPADO) {
            btn.addActionListener(e -> {
                boolean cambio = controlador.alternarEstado(asiento);

                if (!cambio) {
                    javax.swing.JOptionPane.showMessageDialog(this,"Solo puede seleccionar " + maxAsientos + " asientos");
            return;
        }

    actualizarIcono(btn, asiento);
});
        }

        panel.add(btn);
    }


    private void actualizarIcono(JButton btn, ModeloAsientos asiento) {
        switch (asiento.getEstado()) {
            case DISPONIBLE -> btn.setIcon(iconDisponible);
            case SELECCIONADO -> btn.setIcon(iconSeleccionado);
            case OCUPADO -> btn.setIcon(iconOcupado);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoAsientos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoAsientos.setBackground(new java.awt.Color(153, 255, 255));
        fondoAsientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 51, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        fondoAsientos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 51, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        fondoAsientos.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 110, -1, -1));

        jButton1.setText("CONFIRMAR ASIENTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondoAsientos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VuelosFis  (1).png"))); // NOI18N
        fondoAsientos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECCIONE SUS ASIENTOS:");
        fondoAsientos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Disponibles");
        fondoAsientos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 76, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos-disponibles.png"))); // NOI18N
        fondoAsientos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 38, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ocupados");
        fondoAsientos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 76, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos-ocupados.png"))); // NOI18N
        fondoAsientos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 38, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Seleccionados");
        fondoAsientos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 76, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asientos-seleccionados.png"))); // NOI18N
        fondoAsientos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 38, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-azul-asientos (1) (1).jpg"))); // NOI18N
        fondoAsientos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondoAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondoAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.addActionListener(e -> {
        if (!controlador.validarSeleccion()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar exactamente " + maxAsientos + " asientos");
            return;
        }
        JOptionPane.showMessageDialog(this, "Asientos confirmados correctamente");
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoAsientos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
