/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import modelo.ModeloBoleto;
import modelo.ModeloCarrito;
import modelo.ModeloPago;

/**
 *
 * @author Lenovo
 */
public class VistaCarrito extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCarrito.class.getName());

     private ModeloCarrito carrito;
    private DefaultListModel<String> modeloLista;
    
    public VistaCarrito(ModeloCarrito carrito) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.carrito = carrito;
        
        // Inicializar el modelo de lista
        modeloLista = new DefaultListModel<>();
        
        // Cargar los boletos del carrito
        cargarLista();
        
        listaBoletos.setModel(modeloLista);
        
        // Configurar renderer para mejor visualización
        listaBoletos.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, 
                    int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                setText("<html>" + value.toString().replace(" | ", "<br>") + "</html>");
                return this;
            }
        });
    }
   
    private void cargarLista() {
        modeloLista.clear();
        for (ModeloBoleto b : carrito.getBoletos()) {
            String descripcion = b.getNombre() + 
                               " | Clase: " + b.getClaseVuelo() +
                               " | Vuelo: " + b.getVueloSeleccionado() +
                               " | Tipo: " + b.getTipoVuelo() +
                               (b.isTieneMaletas() ? " | Maletas: Sí" : " | Maletas: No") +
                               " | $" + String.format("%.2f", b.getPrecio());
            modeloLista.addElement(descripcion);
        }
        lblTotal.setText("Total: $" + String.format("%.2f", carrito.getTotal()));
    }
    
    public javax.swing.JButton getBtnContinuar() {
        return btnContinuar;
    }
    public void limpiarListeners() {
    for (java.awt.event.ActionListener al : btnContinuar.getActionListeners()) {
        btnContinuar.removeActionListener(al);
    }
}
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        listaBoletos = new javax.swing.JList<>();
        lblTotal = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        listaBoletos.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        jScrollPane12.setViewportView(listaBoletos);

        jPanel1.add(jScrollPane12);
        jScrollPane12.setBounds(60, 140, 860, 330);

        lblTotal.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: ");
        lblTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTotal);
        lblTotal.setBounds(60, 480, 660, 70);

        btnRegresar.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.jpg"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(60, 640, 200, 50);

        btnEliminar.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonT (1).png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(770, 510, 150, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VuelosFis.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(970, 40, 110, 70);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8494.jpg"))); // NOI18N
        jLabel1.setText("BOLETOS A COMPRAR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 30, 1080, 90);

        btnContinuar.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.jpg"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar);
        btnContinuar.setBounds(790, 640, 210, 50);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagobase.jpg"))); // NOI18N
        jPanel1.add(lblFondo);
        lblFondo.setBounds(0, -10, 1080, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     int index = listaBoletos.getSelectedIndex();

    if (index == -1) {
        JOptionPane.showMessageDialog(this,
            "Selecciona un boleto primero");
        return;
    }

    int op = JOptionPane.showConfirmDialog(this,
        "¿Seguro de eliminar este boleto?",
        "Confirmar",
        JOptionPane.YES_NO_OPTION);

    if (op == JOptionPane.YES_OPTION) {
        carrito.eliminar(index);
        modeloLista.remove(index);
        lblTotal.setText("Total a pagar: $" + carrito.getTotal());
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
    VistaPago vistaPago = new VistaPago();
    vistaPago.setCarrito(this.carrito);  // Necesitas crear este método setter
    vistaPago.setVisible(true);
    this.dispose();;

    
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<java.lang.String> listaBoletos;
    // End of variables declaration//GEN-END:variables
}
